server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # Assets com hash podem ter cache longo
  location /assets/ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  # SPA: todas as rotas do React Router voltam para o index.html
  location / {
    try_files $uri $uri/ /index.html;
  }
}
